# Generated by Django 4.2.3 on 2023-07-21 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0016_party_rehearsal_dinner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='is_attending',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='party',
            name='is_attending',
            field=models.BooleanField(default=False),
        ),
    ]
